language: generic
sudo: no
install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - git clone -b origin/master https://github.com/phillord/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-24.3-travis --use --skip
script:
  - ls /home/travis/.evm
  - find /home/travis.evm