language: generic
sudo: no
install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-24.3-travis --use --skip
script:
  - ls .evm
  - find .evm